/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../../src/app/app.module';
import * as i2 from '../../../src/app/app.component';
import * as i3 from '../../node_modules/@angular/material/typings/index.ngfactory';
import * as i4 from './home/home.component.ngfactory';
import * as i5 from './platform/platform.component.ngfactory';
import * as i6 from './simulator/simulator.component.ngfactory';
import * as i7 from './showcase/showcase.component.ngfactory';
import * as i8 from './explore/explore.component.ngfactory';
import * as i9 from './about/about.component.ngfactory';
import * as i10 from './terms/terms.component.ngfactory';
import * as i11 from './app.component.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/cdk/platform';
import * as i14 from '@angular/cdk/scrolling';
import * as i15 from '@angular/cdk/overlay';
import * as i16 from '@angular/cdk/a11y';
import * as i17 from '@angular/cdk/bidi';
import * as i18 from '@angular/platform-browser';
import * as i19 from '@angular/material';
import * as i20 from '@angular/animations/browser';
import * as i21 from '@angular/platform-browser/animations';
import * as i22 from '@angular/router';
import * as i23 from '@angular/animations';
import * as i24 from '@agm/core/utils/browser-globals';
import * as i25 from '@agm/core/services/maps-api-loader/maps-api-loader';
import * as i26 from '@agm/core/services/maps-api-loader/lazy-maps-api-loader';
import * as i27 from '@angular/cdk/portal';
import * as i28 from '../../../src/app/home/home.component';
import * as i29 from '../../../src/app/platform/platform.component';
import * as i30 from '../../../src/app/simulator/simulator.component';
import * as i31 from '../../../src/app/showcase/showcase.component';
import * as i32 from '../../../src/app/explore/explore.component';
import * as i33 from '../../../src/app/about/about.component';
import * as i34 from '../../../src/app/terms/terms.component';
import * as i35 from '../../../src/app/app-routing.module';
import * as i36 from '@agm/core/core.module';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.MdDialogContainerNgFactory,i4.HomeComponentNgFactory,i5.PlatformComponentNgFactory,
              i5.PlatformOverviewComponentNgFactory,i5.PlatformGettingStartedComponentNgFactory,
              i5.PlatformTechspecsComponentNgFactory,i5.PlatformDownloadsComponentNgFactory,
              i6.SimulatorComponentNgFactory,i6.SimulatorOverviewComponentNgFactory,
              i6.SimulatorGettingStartedComponentNgFactory,i6.SimulatorConceptAndStructureComponentNgFactory,
              i6.SimulatorExampleComponentNgFactory,i7.ShowcaseComponentNgFactory,
              i7.SelfPoweredWearablesComponentNgFactory,i7.TransientComputingComponentNgFactory,
              i7.LowPowerIoTComponentNgFactory,i8.ExploreComponentNgFactory,i8.RecommendedReadingComponentNgFactory,
              i8.NVPFundamentalsComponentNgFactory,i9.AboutComponentNgFactory,i10.TermsComponentNgFactory,
              i4.NVPOneMinuteDialogNgFactory,i5.BuyNowDialogNgFactory,i11.AppComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(5120,i0.LOCALE_ID,
          i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i12.NgLocalization,i12.NgLocaleLocalization,
          [i0.LOCALE_ID]),i0.ɵmpd(4608,i13.Platform,i13.Platform,([] as any[])),i0.ɵmpd(5120,
          i14.ScrollDispatcher,i14.SCROLL_DISPATCHER_PROVIDER_FACTORY,[[3,i14.ScrollDispatcher],
              i0.NgZone,i13.Platform]),i0.ɵmpd(5120,i14.ViewportRuler,i14.VIEWPORT_RULER_PROVIDER_FACTORY,
          [[3,i14.ViewportRuler],i14.ScrollDispatcher]),i0.ɵmpd(4608,i15.ScrollStrategyOptions,
          i15.ScrollStrategyOptions,[i14.ScrollDispatcher,i14.ViewportRuler]),i0.ɵmpd(5120,
          i15.OverlayContainer,i15.ɵa,[[3,i15.OverlayContainer]]),i0.ɵmpd(4608,i15.ɵf,
          i15.ɵf,[i14.ViewportRuler]),i0.ɵmpd(4608,i15.Overlay,i15.Overlay,[i15.ScrollStrategyOptions,
          i15.OverlayContainer,i0.ComponentFactoryResolver,i15.ɵf,i0.ApplicationRef,
          i0.Injector,i0.NgZone]),i0.ɵmpd(5120,i15.ɵc,i15.ɵd,[i15.Overlay]),i0.ɵmpd(4608,
          i16.InteractivityChecker,i16.InteractivityChecker,[i13.Platform]),i0.ɵmpd(4608,
          i16.FocusTrapFactory,i16.FocusTrapFactory,[i16.InteractivityChecker,i13.Platform,
              i0.NgZone]),i0.ɵmpd(5120,i16.LiveAnnouncer,i16.LIVE_ANNOUNCER_PROVIDER_FACTORY,
          [[3,i16.LiveAnnouncer],[2,i16.LIVE_ANNOUNCER_ELEMENT_TOKEN],i13.Platform]),
          i0.ɵmpd(6144,i17.DIR_DOCUMENT,(null as any),[i18.DOCUMENT]),i0.ɵmpd(4608,
              i17.Directionality,i17.Directionality,[[2,i17.DIR_DOCUMENT]]),i0.ɵmpd(5120,
              i19.MD_DIALOG_SCROLL_STRATEGY,i19.MD_DIALOG_SCROLL_STRATEGY_PROVIDER_FACTORY,
              [i15.Overlay]),i0.ɵmpd(4608,i19.MdDialog,i19.MdDialog,[i15.Overlay,i0.Injector,
              i19.MD_DIALOG_SCROLL_STRATEGY,[2,i12.Location],[3,i19.MdDialog]]),i0.ɵmpd(5120,
              i0.APP_ID,i0.ɵf,([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,
              ([] as any[])),i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),
          i0.ɵmpd(4608,i18.DomSanitizer,i18.ɵe,[i12.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,
              (null as any),[i18.DomSanitizer]),i0.ɵmpd(4608,i18.HAMMER_GESTURE_CONFIG,
              i18.HammerGestureConfig,([] as any[])),i0.ɵmpd(5120,i18.EVENT_MANAGER_PLUGINS,
              (p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
                return [new i18.ɵDomEventsPlugin(p0_0),new i18.ɵKeyEventsPlugin(p1_0),
                    new i18.ɵHammerGesturesPlugin(p2_0,p2_1)];
              },[i12.DOCUMENT,i12.DOCUMENT,i12.DOCUMENT,i18.HAMMER_GESTURE_CONFIG]),
          i0.ɵmpd(4608,i18.EventManager,i18.EventManager,[i18.EVENT_MANAGER_PLUGINS,
              i0.NgZone]),i0.ɵmpd(135680,i18.ɵDomSharedStylesHost,i18.ɵDomSharedStylesHost,
              [i12.DOCUMENT]),i0.ɵmpd(4608,i18.ɵDomRendererFactory2,i18.ɵDomRendererFactory2,
              [i18.EventManager,i18.ɵDomSharedStylesHost]),i0.ɵmpd(5120,i20.AnimationDriver,
              i21.ɵc,([] as any[])),i0.ɵmpd(5120,i20.ɵAnimationStyleNormalizer,i21.ɵd,
              ([] as any[])),i0.ɵmpd(4608,i20.ɵAnimationEngine,i21.ɵb,[i20.AnimationDriver,
              i20.ɵAnimationStyleNormalizer]),i0.ɵmpd(5120,i0.RendererFactory2,i21.ɵe,
              [i18.ɵDomRendererFactory2,i20.ɵAnimationEngine,i0.NgZone]),i0.ɵmpd(6144,
              i18.ɵSharedStylesHost,(null as any),[i18.ɵDomSharedStylesHost]),i0.ɵmpd(4608,
              i0.Testability,i0.Testability,[i0.NgZone]),i0.ɵmpd(4608,i18.Meta,i18.Meta,
              [i12.DOCUMENT]),i0.ɵmpd(4608,i18.Title,i18.Title,[i12.DOCUMENT]),i0.ɵmpd(5120,
              i22.ActivatedRoute,i22.ɵf,[i22.Router]),i0.ɵmpd(4608,i22.NoPreloading,
              i22.NoPreloading,([] as any[])),i0.ɵmpd(6144,i22.PreloadingStrategy,
              (null as any),[i22.NoPreloading]),i0.ɵmpd(135680,i22.RouterPreloader,
              i22.RouterPreloader,[i22.Router,i0.NgModuleFactoryLoader,i0.Compiler,
                  i0.Injector,i22.PreloadingStrategy]),i0.ɵmpd(4608,i22.PreloadAllModules,
              i22.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i22.ROUTER_INITIALIZER,
              i22.ɵi,[i22.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i22.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i23.AnimationBuilder,i21.ɵBrowserAnimationBuilder,
              [i0.RendererFactory2,i18.DOCUMENT]),i0.ɵmpd(4608,i24.WindowRef,i24.WindowRef,
              ([] as any[])),i0.ɵmpd(4608,i24.DocumentRef,i24.DocumentRef,([] as any[])),
          i0.ɵmpd(4608,i25.MapsAPILoader,i26.LazyMapsAPILoader,[i26.LAZY_MAPS_API_CONFIG,
              i24.WindowRef,i24.DocumentRef]),i0.ɵmpd(512,i12.CommonModule,i12.CommonModule,
              ([] as any[])),i0.ɵmpd(512,i27.PortalModule,i27.PortalModule,([] as any[])),
          i0.ɵmpd(512,i13.PlatformModule,i13.PlatformModule,([] as any[])),i0.ɵmpd(512,
              i14.ScrollDispatchModule,i14.ScrollDispatchModule,([] as any[])),i0.ɵmpd(512,
              i15.OverlayModule,i15.OverlayModule,([] as any[])),i0.ɵmpd(512,i16.A11yModule,
              i16.A11yModule,([] as any[])),i0.ɵmpd(512,i19.CompatibilityModule,i19.CompatibilityModule,
              ([] as any[])),i0.ɵmpd(512,i17.BidiModule,i17.BidiModule,([] as any[])),
          i0.ɵmpd(256,i19.MATERIAL_SANITY_CHECKS,true,([] as any[])),i0.ɵmpd(512,i19.MdCommonModule,
              i19.MdCommonModule,[[2,i18.DOCUMENT],[2,i19.MATERIAL_SANITY_CHECKS]]),
          i0.ɵmpd(512,i19.MdDialogModule,i19.MdDialogModule,([] as any[])),i0.ɵmpd(1024,
              i0.ErrorHandler,i18.ɵa,([] as any[])),i0.ɵmpd(1024,i0.NgProbeToken,() => {
            return [i22.ɵb()];
          },([] as any[])),i0.ɵmpd(512,i22.ɵg,i22.ɵg,[i0.Injector]),i0.ɵmpd(1024,i0.APP_INITIALIZER,
              (p0_0:any,p0_1:any,p1_0:any) => {
                return [i18.ɵc(p0_0,p0_1),i22.ɵh(p1_0)];
              },[[2,i18.NgProbeToken],[2,i0.NgProbeToken],i22.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i18.BrowserModule,i18.BrowserModule,[[3,i18.BrowserModule]]),
          i0.ɵmpd(1024,i22.ɵa,i22.ɵd,[[3,i22.Router]]),i0.ɵmpd(512,i22.UrlSerializer,
              i22.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,i22.ChildrenOutletContexts,
              i22.ChildrenOutletContexts,([] as any[])),i0.ɵmpd(256,i22.ROUTER_CONFIGURATION,
              {},([] as any[])),i0.ɵmpd(1024,i12.LocationStrategy,i22.ɵc,[i12.PlatformLocation,
              [2,i12.APP_BASE_HREF],i22.ROUTER_CONFIGURATION]),i0.ɵmpd(512,i12.Location,
              i12.Location,[i12.LocationStrategy]),i0.ɵmpd(512,i0.Compiler,i0.Compiler,
              ([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,i0.SystemJsNgModuleLoader,
              [i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),i0.ɵmpd(1024,i22.ROUTES,
              () => {
                return [[{path:'',redirectTo:'/home',pathMatch:'full'},{path:'home',
                    component:i28.HomeComponent},{path:'platform',component:i29.PlatformComponent,
                    children:[{path:'',redirectTo:'overview',pathMatch:'full'},{path:'overview',
                        component:i29.PlatformOverviewComponent},{path:'getting-started',
                        component:i29.PlatformGettingStartedComponent},{path:'techspecs',
                        component:i29.PlatformTechspecsComponent},{path:'downloads',
                        component:i29.PlatformDownloadsComponent}]},{path:'simulator',
                    component:i30.SimulatorComponent,children:[{path:'',redirectTo:'overview',
                        pathMatch:'full'},{path:'overview',component:i30.SimulatorOverviewComponent},
                        {path:'getting-started',component:i30.SimulatorGettingStartedComponent},
                        {path:'concept-and-structure',component:i30.SimulatorConceptAndStructureComponent},
                        {path:'example',component:i30.SimulatorExampleComponent}]},
                    {path:'showcase',component:i31.ShowcaseComponent},{path:'showcase/self-powered-wearables',
                        component:i31.SelfPoweredWearablesComponent},{path:'showcase/transient-computing',
                        component:i31.TransientComputingComponent},{path:'showcase/low-power-iot',
                        component:i31.LowPowerIoTComponent},{path:'explore',component:i32.ExploreComponent},
                    {path:'explore/recommended-reading',component:i32.RecommendedReadingComponent},
                    {path:'explore/nvp-fundamentals',component:i32.NVPFundamentalsComponent},
                    {path:'about',component:i33.AboutComponent},{path:'terms-and-conditions',
                        component:i34.TermsComponent},{path:'**',redirectTo:'/home',
                        pathMatch:'full'}]];
              },([] as any[])),i0.ɵmpd(1024,i22.Router,i22.ɵe,[i0.ApplicationRef,i22.UrlSerializer,
              i22.ChildrenOutletContexts,i12.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i22.ROUTES,i22.ROUTER_CONFIGURATION,[2,i22.UrlHandlingStrategy],
              [2,i22.RouteReuseStrategy]]),i0.ɵmpd(512,i22.RouterModule,i22.RouterModule,
              [[2,i22.ɵa],[2,i22.Router]]),i0.ɵmpd(512,i35.AppRoutingModule,i35.AppRoutingModule,
              ([] as any[])),i0.ɵmpd(512,i21.BrowserAnimationsModule,i21.BrowserAnimationsModule,
              ([] as any[])),i0.ɵmpd(512,i36.AgmCoreModule,i36.AgmCoreModule,([] as any[])),
          i0.ɵmpd(512,i1.AppModule,i1.AppModule,([] as any[])),i0.ɵmpd(256,i26.LAZY_MAPS_API_CONFIG,
              {apiKey:'AIzaSyDFquj9AnLZG3zPXBPdovChfCxujtu2V8E'},([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvc3VmYW5nL09uZURyaXZlL05WTGFicy9zcmMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvc3VmYW5nL09uZURyaXZlL05WTGFicy9zcmMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
